language: ruby
rvm:
  - 2.4.2

cache:
  bundler: true
  # directories:
  # - $TEST_DIR/vendor/bundle

services:
  - elasticsearch
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - gem install bundler-audit --no-ri --no-rdoc

script:
  - bundle exec rake db:test:prepare
  - bundle exec rake test
  - bundle audit check --update
  - bundle exec brakeman --exit-on-warn --quiet -f plain
