# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e05f8e5607c97bd21c0e3bb8c06ae1cbd9344a6cf73c4423ee0c020df127a5314f3f5ec2f00fe263476ec0dbcd7d3d0b7007d56e7f1f867b64c1b8a3ef15d880

test:
  secret_key_base: 377c3f1676124859dacad9d74ce00d8d4316feb536052f66dadf39859e25bb0b88c00a0a2e04812df77f23ab9d462868bf00b96de613a19f8589e8810e344334

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 1d95db4a9bc245f63de150d320e5d28f38014e87124c90421e5179d121d13b7a9dab083bb3466fb06a908aaa83a81397f008a0676911a36a9522e8e95f945fb7
